schema = 3

[mod]
  [mod.'github.com/dave/jennifer']
    version = 'v1.7.1'
    hash = 'sha256-tKr4x0m+Nup2X9UyxIK+5ZXzrb1vyfPzc9hD2xh6H6g='

  [mod.'golang.org/x/mod']
    version = 'v0.35.0'
    hash = 'sha256-ICEQxokHywOFInDPqoP+go9l1tZSz3roknF5SXPtNV4='
    goVersion = '1.25.0'

  [mod.'golang.org/x/sync']
    version = 'v0.20.0'
    hash = 'sha256-ybcjhCfK6lroUM0yswUvWooW8MOQZBXyiSqoxG6Uy0Y='

  [mod.'golang.org/x/tools']
    version = 'v0.44.0'
    hash = 'sha256-xuj5FLtSJsAojLLTLXtPdLAIFNTKoVFbDMuqRXmj2W4='
    goVersion = '1.25.0'
