package generate

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Render must be deterministic and Generate must write exactly Render's output —
// otherwise `tommy generate --check` would false-positive on a freshly generated
// file. Also pins OutputPath's <base>_tommy.go convention.
func TestRenderDeterministicMatchesGenerate(t *testing.T) {
	dir := t.TempDir()
	writeFixture(t, dir, "go.mod", "module example.com/test\n\ngo 1.25.6\n")
	writeFixture(t, dir, "config.go", "package test\n\n//go:generate tommy generate\ntype Config struct {\n\tName string `toml:\"name\"`\n}\n")

	if got, want := OutputPath(dir, "config.go"), filepath.Join(dir, "config_tommy.go"); got != want {
		t.Fatalf("OutputPath = %q, want %q", got, want)
	}

	a, err := Render(dir, "config.go")
	if err != nil {
		t.Fatal(err)
	}
	b, err := Render(dir, "config.go")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(a, b) {
		t.Fatal("Render is not deterministic — --check would be unstable")
	}

	if err := Generate(dir, "config.go"); err != nil {
		t.Fatal(err)
	}
	onDisk, err := os.ReadFile(OutputPath(dir, "config.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(onDisk, a) {
		t.Fatal("Generate output != Render output — --check would false-positive on a fresh file")
	}
}

func TestGenerateProducesValidFile(t *testing.T) {
	dir := t.TempDir()
	writeFixture(t, dir, "go.mod", "module example.com/test\n\ngo 1.25.6\n")
	writeFixture(t, dir, "config.go", "package test\n\n//go:generate tommy generate\ntype Config struct {\n\tName    string `toml:\"name\"`\n\tPort    int    `toml:\"port\"`\n\tEnabled bool   `toml:\"enabled\"`\n}\n")

	err := Generate(dir, "config.go")
	if err != nil {
		t.Fatal(err)
	}

	outPath := filepath.Join(dir, "config_tommy.go")
	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("generated file not found: %v", err)
	}

	out := string(data)
	// In-process generation uses the dev/unknown defaults (no ldflags), so the
	// header carries the version stamp in its dev form (#125).
	if !strings.Contains(out, "Code generated by tommy dev (unknown); DO NOT EDIT.") {
		t.Fatal("missing version-stamped generated header")
	}
	if !strings.Contains(out, "ConfigDocument") {
		t.Fatal("missing ConfigDocument")
	}
	if !strings.Contains(out, "DecodeConfig") {
		t.Fatal("missing DecodeConfig")
	}
}

// The generated header records the producing tommy build (version + commit, with
// a -dirty commit suffix flowing through verbatim) so a binary↔library skew is
// visible in the output (#125).
func TestRenderFileHeaderStampsVersion(t *testing.T) {
	origV, origC := BuildVersion, BuildCommit
	BuildVersion, BuildCommit = "0.4.0", "abc1234-dirty"
	defer func() { BuildVersion, BuildCommit = origV, origC }()

	var b strings.Builder
	if err := RenderFile(&b, "x", nil); err != nil {
		t.Fatal(err)
	}
	if want := "// Code generated by tommy 0.4.0 (abc1234-dirty); DO NOT EDIT."; !strings.Contains(b.String(), want) {
		t.Fatalf("header not stamped:\nwant substring: %s\ngot:\n%s", want, b.String())
	}
}
