package generate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateProducesValidFile(t *testing.T) {
	dir := t.TempDir()
	writeFixture(t, dir, "go.mod", "module example.com/test\n\ngo 1.25.6\n")
	writeFixture(t, dir, "config.go", "package test\n\n//go:generate tommy generate\ntype Config struct {\n\tName    string `toml:\"name\"`\n\tPort    int    `toml:\"port\"`\n\tEnabled bool   `toml:\"enabled\"`\n}\n")

	err := Generate(dir, "config.go")
	if err != nil {
		t.Fatal(err)
	}

	outPath := filepath.Join(dir, "config_tommy.go")
	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("generated file not found: %v", err)
	}

	out := string(data)
	if !strings.Contains(out, "Code generated by tommy; DO NOT EDIT.") {
		t.Fatal("missing generated header")
	}
	if !strings.Contains(out, "ConfigDocument") {
		t.Fatal("missing ConfigDocument")
	}
	if !strings.Contains(out, "DecodeConfig") {
		t.Fatal("missing DecodeConfig")
	}
}
