package generate

import (
	"io"
	"strings"

	jen "github.com/dave/jennifer/jen"
)

const (
	cstPkg = "github.com/amarbel-llc/tommy/pkg/cst"
	docPkg = "github.com/amarbel-llc/tommy/pkg/document"
)

// jenCtx carries context for decode rendering within one function scope.
type jenCtx struct {
	consumed *jen.Statement
	retErr   func(fmtStr string, args ...jen.Code) jen.Code
	docVar   *jen.Statement
}

func receiverJenCtx() jenCtx {
	return jenCtx{
		consumed: jen.Id("d").Dot("consumed"),
		retErr: func(f string, a ...jen.Code) jen.Code {
			args := []jen.Code{jen.Lit(f)}
			args = append(args, a...)
			return jen.Return(jen.Nil(), jen.Qual("fmt", "Errorf").Call(args...))
		},
		docVar: jen.Id("d").Dot("cstDoc"),
	}
}

func freeJenCtx() jenCtx {
	return jenCtx{
		consumed: jen.Id("consumed"),
		retErr: func(f string, a ...jen.Code) jen.Code {
			args := []jen.Code{jen.Lit(f)}
			args = append(args, a...)
			return jen.Return(jen.Qual("fmt", "Errorf").Call(args...))
		},
		docVar: jen.Id("doc"),
	}
}

func (c jenCtx) mc(key TOMLKey) jen.Code {
	return c.consumed.Clone().Index(key.Jen()).Op("=").True()
}

func (c jenCtx) mcExpr(expr *jen.Statement) jen.Code {
	return c.consumed.Clone().Index(expr).Op("=").True()
}

func (c jenCtx) root() *jen.Statement {
	return c.docVar.Clone().Dot("Root").Call().Dot("Children")
}

// --- File generation ---

func RenderFileJen(w io.Writer, pkg string, structs []StructInfo) error {
	f := jen.NewFile(pkg)
	f.NoFormat = true
	f.HeaderComment("Code generated by tommy; DO NOT EDIT.")
	f.ImportName("fmt", "fmt")
	f.ImportName(cstPkg, "cst")
	f.ImportName(docPkg, "document")
	f.ImportName("strings", "strings")
	for _, p := range collectImportPaths(structs) {
		parts := strings.Split(p, "/")
		f.ImportName(p, parts[len(parts)-1])
	}
	f.Var().Defs(
		jen.Id("_").Op("=").Qual("fmt", "Errorf"),
		jen.Id("_").Qual(cstPkg, "NodeKind"),
		jen.Id("_").Op("=").Qual("strings", "Contains"),
	)
	for _, si := range structs {
		jenEmitStruct(f, si)
	}
	return f.Render(w)
}

func jenEmitStruct(f *jen.File, si StructInfo) {
	dt := si.Name + "Document"
	for _, fi := range si.Fields {
		if isSamePackageSliceStruct(fi) {
			f.Type().Id(unexport(fi.TypeName) + "Handle").Struct(jen.Id("node").Op("*").Qual(cstPkg, "Node"))
		}
	}
	f.Type().Id(dt).StructFunc(func(g *jen.Group) {
		g.Id("data").Id(si.Name)
		g.Id("cstDoc").Op("*").Qual(docPkg, "Document")
		g.Id("consumed").Map(jen.String()).Bool()
		for _, fi := range si.Fields {
			if isSamePackageSliceStruct(fi) {
				g.Id(unexport(fi.GoName)).Index().Id(unexport(fi.TypeName) + "Handle")
			}
		}
	})
	jenEmitDecode(f, si, dt)
	f.Func().Params(jen.Id("d").Op("*").Id(dt)).Id("Data").Params().Op("*").Id(si.Name).Block(
		jen.Return(jen.Op("&").Id("d").Dot("data")),
	)
	jenEmitEncode(f, si, dt)
	f.Func().Params(jen.Id("d").Op("*").Id(dt)).Id("Undecoded").Params().Index().String().Block(
		jen.Return(jen.Qual(docPkg, "UndecodedKeys").Call(jen.Id("d").Dot("cstDoc").Dot("Root").Call(), jen.Id("d").Dot("consumed"))),
	)
	for _, m := range []struct{ n, d string }{
		{"Comment", "GetComment"},
		{"SetComment", "SetComment"},
		{"InlineComment", "GetInlineComment"},
		{"SetInlineComment", "SetInlineComment"},
	} {
		if strings.HasPrefix(m.n, "Set") {
			f.Func().Params(jen.Id("d").Op("*").Id(dt)).Id(m.n).Params(jen.Id("key"), jen.Id("comment").String()).Block(
				jen.Id("d").Dot("cstDoc").Dot(m.d).Call(jen.Id("key"), jen.Id("comment")),
			)
		} else {
			f.Func().Params(jen.Id("d").Op("*").Id(dt)).Id(m.n).Params(jen.Id("key").String()).String().Block(
				jen.Return(jen.Id("d").Dot("cstDoc").Dot(m.d).Call(jen.Id("key"))),
			)
		}
	}
	jenEmitDecodeInto(f, si)
	jenEmitEncodeFrom(f, si)
}

func jenEmitDecode(f *jen.File, si StructInfo, dt string) {
	ctx := receiverJenCtx()
	ops := buildDecodeOps(si, "d.data", "", ReceiverTarget("d", "data"), StaticKey(""), true, true)
	f.Func().Id("Decode"+si.Name).Params(jen.Id("input").Index().Byte()).Params(jen.Op("*").Id(dt), jen.Error()).BlockFunc(func(g *jen.Group) {
		g.List(jen.Id("doc"), jen.Err()).Op(":=").Qual(docPkg, "Parse").Call(jen.Id("input"))
		g.If(jen.Err().Op("!=").Nil()).Block(jen.Return(jen.Nil(), jen.Err()))
		g.Empty()
		g.Id("d").Op(":=").Op("&").Id(dt).Values(jen.Dict{
			jen.Id("cstDoc"):   jen.Id("doc"),
			jen.Id("consumed"): jen.Make(jen.Map(jen.String()).Bool()),
		})
		g.Empty()
		for _, s := range jenDecodeOps(ctx, ops, jen.Id("d").Dot("cstDoc").Dot("Root").Call(), "") {
			g.Add(s)
		}
		if si.Validatable {
			g.If(jen.Err().Op(":=").Id("d").Dot("data").Dot("Validate").Call(), jen.Err().Op("!=").Nil()).Block(
				jen.Return(jen.Nil(), jen.Qual("fmt", "Errorf").Call(jen.Lit("validation failed: %w"), jen.Err())),
			)
		}
		g.Return(jen.Id("d"), jen.Nil())
	})
}

func jenEmitEncode(f *jen.File, si StructInfo, dt string) {
	ectx := receiverEncCtx()
	ops := buildEncodeOps(si, ReceiverTarget("d", "data"), StaticKey(""), true, true)
	f.Func().Params(jen.Id("d").Op("*").Id(dt)).Id("Encode").Params().Params(jen.Index().Byte(), jen.Error()).BlockFunc(func(g *jen.Group) {
		if si.Validatable {
			g.If(jen.Err().Op(":=").Id("d").Dot("data").Dot("Validate").Call(), jen.Err().Op("!=").Nil()).Block(
				jen.Return(jen.Nil(), jen.Qual("fmt", "Errorf").Call(jen.Lit("validation failed: %w"), jen.Err())),
			)
		}
		for _, s := range jenEncodeOps(ectx, ops, jen.Id("d").Dot("cstDoc").Dot("Root").Call()) {
			g.Add(s)
		}
		g.Return(jen.Id("d").Dot("cstDoc").Dot("Bytes").Call(), jen.Nil())
	})
}

func jenEmitDecodeInto(f *jen.File, si StructInfo) {
	ctx := freeJenCtx()
	ops := buildDecodeOps(si, "data", "", LocalTarget("data"), PrefixedKey(""), false, false)
	f.Func().Id("Decode"+si.Name+"Into").Params(
		jen.Id("data").Op("*").Id(si.Name),
		jen.Id("doc").Op("*").Qual(docPkg, "Document"),
		jen.Id("container").Op("*").Qual(cstPkg, "Node"),
		jen.Id("consumed").Map(jen.String()).Bool(),
		jen.Id("keyPrefix").String(),
	).Error().BlockFunc(func(g *jen.Group) {
		for _, s := range jenDecodeOps(ctx, ops, jen.Id("container"), "") {
			g.Add(s)
		}
		g.Return(jen.Nil())
	})
}

func jenEmitEncodeFrom(f *jen.File, si StructInfo) {
	ectx := freeEncCtx()
	ops := buildEncodeOps(si, LocalTarget("data"), StaticKey(""), false, false)
	f.Func().Id("Encode"+si.Name+"From").Params(
		jen.Id("data").Op("*").Id(si.Name),
		jen.Id("doc").Op("*").Qual(docPkg, "Document"),
		jen.Id("container").Op("*").Qual(cstPkg, "Node"),
	).Error().BlockFunc(func(g *jen.Group) {
		for _, s := range jenEncodeOps(ectx, ops, jen.Id("container")) {
			g.Add(s)
		}
		g.Return(jen.Nil())
	})
}

// --- Decode ops ---

func jenDecodeOps(ctx jenCtx, ops []DecodeOp, cv *jen.Statement, fv string) []jen.Code {
	var leaf, cont []DecodeOp
	for _, op := range ops {
		switch op.(type) {
		case GetPrimitive, GetCustom, GetTextMarshaler, GetSlicePrimitive, GetSliceTextMarshaler:
			leaf = append(leaf, op)
		default:
			cont = append(cont, op)
		}
	}
	var out []jen.Code
	if len(leaf) > 0 {
		out = append(out, jenLeafScan(ctx, leaf, cv, fv))
	}
	for _, op := range cont {
		out = append(out, jenContOp(ctx, op, cv, fv)...)
	}
	return out
}

func jenLeafScan(ctx jenCtx, ops []DecodeOp, cv *jen.Statement, fv string) jen.Code {
	var cases []jen.Code
	for _, op := range ops {
		cases = append(cases, jenLeafCase(ctx, op, fv)...)
	}
	return jen.For(jen.List(jen.Id("_"), jen.Id("_kv")).Op(":=").Range().Add(cv.Clone()).Dot("Children")).Block(
		jen.If(jen.Id("_kv").Dot("Kind").Op("!=").Qual(cstPkg, "NodeKeyValue")).Block(jen.Continue()),
		jen.Switch(jen.Qual(cstPkg, "KeyValueName").Call(jen.Id("_kv"))).Block(cases...),
	)
}

func jenLeafCase(ctx jenCtx, op DecodeOp, fv string) []jen.Code {
	switch o := op.(type) {
	case GetPrimitive:
		ei := cstExtract(o.TypeName)
		bk := o.TKey.BareKey()
		var body []jen.Code
		if o.Pointer {
			if ei.cast != "" {
				body = append(body, jen.Id("_cv").Op(":=").Id(ei.cast).Call(jen.Id("v")), o.Tgt.Jen().Clone().Op("=").Op("&").Id("_cv"))
			} else {
				body = append(body, o.Tgt.Jen().Clone().Op("=").Op("&").Id("v"))
			}
		} else if o.ElemType != "" {
			et := jenType(o.ElemType, o.ImportPath)
			if ei.cast != "" {
				body = append(body, o.Tgt.Jen().Clone().Op("=").Add(et).Call(jen.Id(ei.cast).Call(jen.Id("v"))))
			} else {
				body = append(body, o.Tgt.Jen().Clone().Op("=").Add(et).Call(jen.Id("v")))
			}
		} else if ei.cast != "" {
			body = append(body, o.Tgt.Jen().Clone().Op("=").Id(ei.cast).Call(jen.Id("v")))
		} else {
			body = append(body, o.Tgt.Jen().Clone().Op("=").Id("v"))
		}
		if fv != "" {
			body = append(body, jen.Id(fv).Op("=").True())
		}
		body = append(body, ctx.mc(o.TKey))
		return []jen.Code{jen.Case(jen.Lit(bk)).Block(
			jen.If(jen.List(jen.Id("v"), jen.Id("ok")).Op(":=").Qual(cstPkg, ei.fn).Call(jen.Id("_kv")), jen.Id("ok")).Block(body...),
		)}
	case GetCustom:
		bk := o.TKey.BareKey()
		var body []jen.Code
		body = append(body, jen.If(jen.Err().Op(":=").Add(o.Tgt.Jen().Clone()).Dot("UnmarshalTOML").Call(jen.Id("raw")), jen.Err().Op("!=").Nil()).Block(ctx.retErr(bk+": %w", jen.Err())))
		if fv != "" {
			body = append(body, jen.Id(fv).Op("=").True())
		}
		body = append(body, ctx.mc(o.TKey))
		return []jen.Code{jen.Case(jen.Lit(bk)).Block(
			jen.If(jen.List(jen.Id("raw"), jen.Id("ok")).Op(":=").Qual(cstPkg, "ExtractRaw").Call(jen.Id("_kv")), jen.Id("ok")).Block(body...),
		)}
	case GetTextMarshaler:
		bk := o.TKey.BareKey()
		var body []jen.Code
		body = append(body, jen.If(jen.Err().Op(":=").Add(o.Tgt.Jen().Clone()).Dot("UnmarshalText").Call(jen.Index().Byte().Call(jen.Id("v"))), jen.Err().Op("!=").Nil()).Block(ctx.retErr(bk+": %w", jen.Err())))
		if fv != "" {
			body = append(body, jen.Id(fv).Op("=").True())
		}
		body = append(body, ctx.mc(o.TKey))
		return []jen.Code{jen.Case(jen.Lit(bk)).Block(
			jen.If(jen.List(jen.Id("v"), jen.Id("ok")).Op(":=").Qual(cstPkg, "ExtractString").Call(jen.Id("_kv")), jen.Id("ok")).Block(body...),
		)}
	case GetSlicePrimitive:
		bk := o.TKey.BareKey()
		var body []jen.Code
		if o.SlicePointer {
			body = append(body,
				o.Tgt.Jen().Clone().Op("=").Make(jen.Index().Op("*").Id(o.ElemType), jen.Len(jen.Id("v"))),
				jen.For(jen.Id("_si").Op(":=").Range().Id("v")).Block(o.Tgt.Jen().Clone().Index(jen.Id("_si")).Op("=").Op("&").Id("v").Index(jen.Id("_si"))),
			)
		} else if o.TypeName != "" {
			body = append(body, o.Tgt.Jen().Clone().Op("=").Add(jenType(o.TypeName, o.ImportPath)).Call(jen.Id("v")))
		} else {
			body = append(body, o.Tgt.Jen().Clone().Op("=").Id("v"))
		}
		body = append(body, ctx.mc(o.TKey))
		return []jen.Code{jen.Case(jen.Lit(bk)).Block(
			jen.If(jen.List(jen.Id("v"), jen.Id("ok")).Op(":=").Qual(cstPkg, cstSliceExtractFunc(o.ElemType)).Call(jen.Id("_kv")), jen.Id("ok")).Block(body...),
		)}
	case GetSliceTextMarshaler:
		bk := o.TKey.BareKey()
		return []jen.Code{jen.Case(jen.Lit(bk)).Block(
			jen.If(jen.List(jen.Id("v"), jen.Id("ok")).Op(":=").Qual(cstPkg, "ExtractStringSlice").Call(jen.Id("_kv")), jen.Id("ok")).Block(
				o.Tgt.Jen().Clone().Op("=").Make(jen.Index().Add(jenType(o.TypeName, o.ImportPath)), jen.Len(jen.Id("v"))),
				jen.For(jen.List(jen.Id("_si"), jen.Id("_s")).Op(":=").Range().Id("v")).Block(
					jen.If(jen.Err().Op(":=").Add(o.Tgt.Jen().Clone()).Index(jen.Id("_si")).Dot("UnmarshalText").Call(jen.Index().Byte().Call(jen.Id("_s"))), jen.Err().Op("!=").Nil()).Block(ctx.retErr(bk+"[%d]: %w", jen.Id("_si"), jen.Err())),
				),
				ctx.mc(o.TKey),
			),
		)}
	}
	return nil
}

// --- Container ops ---

func jenContOp(ctx jenCtx, op DecodeOp, cv *jen.Statement, fv string) []jen.Code {
	switch o := op.(type) {
	case GetMapStringString:
		return jenMSS(ctx, o, fv)
	case GetMapStringMapStringString:
		return jenMSS2(ctx, o)
	case InTable:
		return jenIT(ctx, o)
	case InPointerTable:
		return jenIPT(ctx, o, cv)
	case ForArrayTable:
		return jenFAT(ctx, o, fv)
	case ForMapStringStruct:
		return jenFMS(ctx, o)
	case DelegateStruct:
		return jenDS(ctx, o)
	case DelegateSlice:
		return jenDSl(ctx, o, fv)
	case DelegateMap:
		return jenDM(ctx, o)
	case WithFoundVar:
		return jenContOp(ctx, o.Inner, cv, o.FoundVar)
	}
	return nil
}

func tableMatch(key TOMLKey) *jen.Statement {
	return jen.Id("_ch").Dot("Kind").Op("==").Qual(cstPkg, "NodeTable").Op("&&").Qual(cstPkg, "TableHeaderKey").Call(jen.Id("_ch")).Op("==").Add(key.Jen())
}

func jenMSS(ctx jenCtx, o GetMapStringString, fv string) []jen.Code {
	return []jen.Code{jen.For(jen.List(jen.Id("_"), jen.Id("_ch")).Op(":=").Range().Add(ctx.root())).Block(
		jen.If(tableMatch(o.TKey)).BlockFunc(func(g *jen.Group) {
			g.Add(o.Tgt.Jen().Clone()).Op("=").Qual(cstPkg, "ExtractStringMap").Call(jen.Id("_ch"))
			if fv != "" {
				g.Id(fv).Op("=").True()
			}
			g.Add(ctx.mc(o.TKey))
			g.For(jen.Id("_ik").Op(":=").Range().Add(o.Tgt.Jen().Clone())).Block(ctx.mcExpr(o.TKey.Jen().Op("+").Lit(".").Op("+").Id("_ik")))
			g.Break()
		}),
	)}
}

func jenMSS2(ctx jenCtx, o GetMapStringMapStringString) []jen.Code {
	pf := o.TKey.Lit(".")
	return []jen.Code{jen.BlockFunc(func(g *jen.Group) {
		if o.TypeName != "" {
			g.Var().Id("_mr").Map(jen.String()).Id(o.TypeName)
		} else {
			g.Var().Id("_mr").Map(jen.String()).Map(jen.String()).String()
		}
		g.For(jen.List(jen.Id("_"), jen.Id("_ch")).Op(":=").Range().Add(ctx.root())).BlockFunc(func(g *jen.Group) {
			g.If(jen.Id("_ch").Dot("Kind").Op("!=").Qual(cstPkg, "NodeTable")).Block(jen.Continue())
			g.Id("_hdr").Op(":=").Qual(cstPkg, "TableHeaderKey").Call(jen.Id("_ch"))
			g.If(jen.Op("!").Qual("strings", "HasPrefix").Call(jen.Id("_hdr"), pf.Jen())).Block(jen.Continue())
			g.Id("_mk").Op(":=").Id("_hdr").Index(pf.JenLen().Op(":"))
			g.If(jen.Id("_mr").Op("==").Nil()).BlockFunc(func(g *jen.Group) {
				g.Add(ctx.mc(o.TKey))
				if o.TypeName != "" {
					g.Id("_mr").Op("=").Make(jen.Map(jen.String()).Id(o.TypeName))
				} else {
					g.Id("_mr").Op("=").Make(jen.Map(jen.String()).Map(jen.String()).String())
				}
			})
			g.Add(ctx.mcExpr(o.TKey.Jen().Op("+").Lit(".").Op("+").Id("_mk")))
			g.Id("_inner").Op(":=").Qual(cstPkg, "ExtractStringMap").Call(jen.Id("_ch"))
			g.For(jen.Id("_ik").Op(":=").Range().Id("_inner")).Block(ctx.mcExpr(o.TKey.Jen().Op("+").Lit(".").Op("+").Id("_mk").Op("+").Lit(".").Op("+").Id("_ik")))
			if o.TypeName != "" {
				g.Id("_mr").Index(jen.Id("_mk")).Op("=").Id(o.TypeName).Call(jen.Id("_inner"))
			} else {
				g.Id("_mr").Index(jen.Id("_mk")).Op("=").Id("_inner")
			}
		})
		g.If(jen.Id("_mr").Op("!=").Nil()).Block(o.Tgt.Jen().Clone().Op("=").Id("_mr"))
	})}
}

func jenIT(ctx jenCtx, o InTable) []jen.Code {
	return []jen.Code{jen.For(jen.List(jen.Id("_"), jen.Id("_ch")).Op(":=").Range().Add(ctx.root())).Block(
		jen.If(tableMatch(o.TKey)).BlockFunc(func(g *jen.Group) {
			g.Add(ctx.mc(o.TKey))
			for _, s := range jenDecodeOps(ctx, o.Fields, jen.Id("_ch"), "") {
				g.Add(s)
			}
			g.Break()
		}),
	)}
}

func jenIPT(ctx jenCtx, o InPointerTable, cv *jen.Statement) []jen.Code {
	lv := toLowerFirst(o.Tgt.Segs[len(o.Tgt.Segs)-1].Name) + "Val"
	return []jen.Code{jen.BlockFunc(func(g *jen.Group) {
		g.Var().Id("_ft").Op("*").Qual(cstPkg, "Node")
		g.For(jen.List(jen.Id("_"), jen.Id("_ch")).Op(":=").Range().Add(ctx.root())).Block(
			jen.If(tableMatch(o.TKey)).Block(jen.Id("_ft").Op("=").Id("_ch"), jen.Break()),
		)
		g.If(jen.Id("_ft").Op("!=").Nil()).BlockFunc(func(g *jen.Group) {
			g.Add(ctx.mc(o.TKey))
			g.Id(lv).Op(":=").Op("&").Id(o.TypeName).Values()
			for _, s := range jenDecodeOps(ctx, o.TableFields, jen.Id("_ft"), "") {
				g.Add(s)
			}
			g.Add(o.Tgt.Jen().Clone()).Op("=").Id(lv)
		}).Else().BlockFunc(func(g *jen.Group) {
			g.Id(lv).Op(":=").Op("&").Id(o.TypeName).Values()
			g.Id("_found").Op(":=").False()
			for _, s := range jenDecodeOps(ctx, o.FlatFields, cv.Clone(), "_found") {
				g.Add(s)
			}
			g.If(jen.Id("_found")).Block(o.Tgt.Jen().Clone().Op("=").Id(lv))
		})
	})}
}

func jenFAT(ctx jenCtx, o ForArrayTable, fv string) []jen.Code {
	nv := "_" + tomlKey(o.Key) + "Nodes"
	var collect jen.Code
	if o.TDottedKey.IsStatic() {
		collect = jen.For(jen.List(jen.Id("_"), jen.Id("_ch")).Op(":=").Range().Add(ctx.root())).Block(
			jen.If(jen.Id("_ch").Dot("Kind").Op("==").Qual(cstPkg, "NodeArrayTable").Op("&&").Qual(cstPkg, "TableHeaderKey").Call(jen.Id("_ch")).Op("==").Add(o.TDottedKey.Jen())).Block(
				jen.Id(nv).Op("=").Append(jen.Id(nv), jen.Id("_ch")),
			),
		)
	} else {
		collect = jen.Id(nv).Op("=").Add(ctx.docVar.Clone()).Dot("FindArrayTableNodes").Call(o.TDottedKey.Jen())
	}
	var stmts []jen.Code
	stmts = append(stmts, jen.Var().Id(nv).Index().Op("*").Qual(cstPkg, "Node"), collect)
	if fv != "" {
		stmts = append(stmts, jen.If(jen.Len(jen.Id(nv)).Op(">").Lit(0)).Block(jen.Id(fv).Op("=").True()))
	}
	if o.TrackHandles {
		hn := toLowerFirst(o.TypeName) + "Handle"
		fn := toLowerFirst(o.Tgt.Segs[len(o.Tgt.Segs)-1].Name)
		stmts = append(stmts, jen.Id("d").Dot(fn).Op("=").Make(jen.Index().Id(hn), jen.Len(jen.Id(nv))))
	}
	jt := jenType(o.TypeName, o.ImportPath)
	if o.SlicePointer {
		stmts = append(stmts, o.Tgt.Jen().Clone().Op("=").Make(jen.Index().Op("*").Add(jt.Clone()), jen.Len(jen.Id(nv))))
	} else {
		stmts = append(stmts, o.Tgt.Jen().Clone().Op("=").Make(jen.Index().Add(jt.Clone()), jen.Len(jen.Id(nv))))
	}
	stmts = append(stmts, ctx.mc(o.TDottedKey))
	stmts = append(stmts, jen.For(jen.List(jen.Id("i"), jen.Id("_node")).Op(":=").Range().Id(nv)).BlockFunc(func(g *jen.Group) {
		if o.TrackHandles {
			hn := toLowerFirst(o.TypeName) + "Handle"
			fn := toLowerFirst(o.Tgt.Segs[len(o.Tgt.Segs)-1].Name)
			g.Id("d").Dot(fn).Index(jen.Id("i")).Op("=").Id(hn).Values(jen.Dict{jen.Id("node"): jen.Id("_node")})
		}
		if o.SlicePointer {
			g.Add(o.Tgt.Jen().Clone()).Index(jen.Id("i")).Op("=").Op("&").Add(jt.Clone()).Values()
		}
		jenArrayEntry(ctx, g, o.Fields, o.TDottedKey)
	}))
	return stmts
}

func jenArrayEntry(ctx jenCtx, g *jen.Group, ops []DecodeOp, pk TOMLKey) {
	var leaf, cont []DecodeOp
	for _, op := range ops {
		switch op.(type) {
		case GetPrimitive, GetCustom, GetTextMarshaler, GetSlicePrimitive, GetSliceTextMarshaler:
			leaf = append(leaf, op)
		default:
			cont = append(cont, op)
		}
	}
	if len(leaf) > 0 {
		g.Add(jenLeafScan(ctx, leaf, jen.Id("_node"), ""))
	}
	for _, op := range cont {
		for _, s := range jenPosOp(ctx, op, pk) {
			g.Add(s)
		}
	}
}

func jenFMS(ctx jenCtx, o ForMapStringStruct) []jen.Code {
	pf := o.TKey.Lit(".")
	return []jen.Code{jen.BlockFunc(func(g *jen.Group) {
		if o.SlicePointer {
			g.Var().Id("_mr").Map(jen.String()).Op("*").Id(o.TypeName)
		} else {
			g.Var().Id("_mr").Map(jen.String()).Id(o.TypeName)
		}
		g.For(jen.List(jen.Id("_"), jen.Id("_ch")).Op(":=").Range().Add(ctx.root())).BlockFunc(func(g *jen.Group) {
			g.If(jen.Id("_ch").Dot("Kind").Op("!=").Qual(cstPkg, "NodeTable")).Block(jen.Continue())
			g.Id("_hdr").Op(":=").Qual(cstPkg, "TableHeaderKey").Call(jen.Id("_ch"))
			g.If(jen.Op("!").Qual("strings", "HasPrefix").Call(jen.Id("_hdr"), pf.Jen())).Block(jen.Continue())
			g.Id("_mk").Op(":=").Id("_hdr").Index(pf.JenLen().Op(":"))
			g.If(jen.Qual("strings", "Contains").Call(jen.Id("_mk"), jen.Lit("."))).Block(jen.Continue())
			g.If(jen.Id("_mr").Op("==").Nil()).BlockFunc(func(g *jen.Group) {
				g.Add(ctx.mc(o.TKey))
				if o.SlicePointer {
					g.Id("_mr").Op("=").Make(jen.Map(jen.String()).Op("*").Id(o.TypeName))
				} else {
					g.Id("_mr").Op("=").Make(jen.Map(jen.String()).Id(o.TypeName))
				}
			})
			g.Add(ctx.mcExpr(o.TKey.Jen().Op("+").Lit(".").Op("+").Id("_mk")))
			g.Var().Id("entry").Id(o.TypeName)
			innerOps := injectMapKey(o.Fields, "_mk", o.TKey)
			for _, s := range jenDecodeOps(ctx, innerOps, jen.Id("_ch"), "") {
				g.Add(s)
			}
			if o.SlicePointer {
				g.Id("_mr").Index(jen.Id("_mk")).Op("=").Op("&").Id("entry")
			} else {
				g.Id("_mr").Index(jen.Id("_mk")).Op("=").Id("entry")
			}
		})
		g.If(jen.Id("_mr").Op("!=").Nil()).Block(o.Tgt.Jen().Clone().Op("=").Id("_mr"))
	})}
}

// --- Positional ops ---

func jenPosOp(ctx jenCtx, op DecodeOp, pk TOMLKey) []jen.Code {
	switch o := op.(type) {
	case InTable:
		return jenPIT(ctx, o, pk)
	case GetMapStringString:
		return jenPMSS(ctx, o, pk)
	case ForArrayTable:
		return jenPFAT(ctx, o, pk)
	case InPointerTable:
		return jenPIPT(ctx, o, pk)
	case ForMapStringStruct:
		return jenPFMS(ctx, o, pk)
	case DelegateStruct:
		return jenDS(ctx, o)
	case DelegateSlice:
		return jenDSl(ctx, o, "")
	case DelegateMap:
		return jenDM(ctx, o)
	case WithFoundVar:
		return jenPosOp(ctx, o.Inner, pk)
	}
	return nil
}

func posHeader(pk TOMLKey) jen.Code {
	return jen.If(jen.Id("_rc").Dot("Kind").Op("==").Qual(cstPkg, "NodeArrayTable").Op("&&").Qual(cstPkg, "TableHeaderKey").Call(jen.Id("_rc")).Op("==").Add(pk.Jen())).Block(
		jen.If(jen.Id("_pi").Op(">").Id("i")).Block(jen.Break()),
		jen.Id("_pi").Op("++"), jen.Continue(),
	)
}

func jenPIT(ctx jenCtx, o InTable, pk TOMLKey) []jen.Code {
	return []jen.Code{jen.BlockFunc(func(g *jen.Group) {
		g.Id("_pi").Op(":=").Lit(0)
		g.For(jen.List(jen.Id("_"), jen.Id("_rc")).Op(":=").Range().Add(ctx.root())).BlockFunc(func(g *jen.Group) {
			g.Add(posHeader(pk))
			g.If(jen.Id("_pi").Op("==").Id("i").Op("+").Lit(1).Op("&&").Id("_rc").Dot("Kind").Op("==").Qual(cstPkg, "NodeTable").Op("&&").Qual(cstPkg, "TableHeaderKey").Call(jen.Id("_rc")).Op("==").Add(o.TKey.Jen())).BlockFunc(func(g *jen.Group) {
				g.Add(ctx.mc(o.TKey))
				for _, s := range jenDecodeOps(ctx, o.Fields, jen.Id("_rc"), "") {
					g.Add(s)
				}
				g.Break()
			})
		})
	})}
}

func jenPMSS(ctx jenCtx, o GetMapStringString, pk TOMLKey) []jen.Code {
	return []jen.Code{jen.BlockFunc(func(g *jen.Group) {
		g.Id("_pi").Op(":=").Lit(0)
		g.For(jen.List(jen.Id("_"), jen.Id("_rc")).Op(":=").Range().Add(ctx.root())).BlockFunc(func(g *jen.Group) {
			g.Add(posHeader(pk))
			g.If(jen.Id("_pi").Op("==").Id("i").Op("+").Lit(1).Op("&&").Id("_rc").Dot("Kind").Op("==").Qual(cstPkg, "NodeTable").Op("&&").Qual(cstPkg, "TableHeaderKey").Call(jen.Id("_rc")).Op("==").Add(o.TKey.Jen())).BlockFunc(func(g *jen.Group) {
				g.Add(o.Tgt.Jen().Clone()).Op("=").Qual(cstPkg, "ExtractStringMap").Call(jen.Id("_rc"))
				g.Add(ctx.mc(o.TKey))
				g.For(jen.Id("_ik").Op(":=").Range().Add(o.Tgt.Jen().Clone())).Block(ctx.mcExpr(o.TKey.Jen().Op("+").Lit(".").Op("+").Id("_ik")))
				g.Break()
			})
		})
	})}
}

func jenPFAT(ctx jenCtx, o ForArrayTable, pk TOMLKey) []jen.Code {
	nv := "_" + tomlKey(o.Key) + "Nodes"
	return []jen.Code{jen.BlockFunc(func(g *jen.Group) {
		g.Var().Id(nv).Index().Op("*").Qual(cstPkg, "Node")
		g.Id("_pi").Op(":=").Lit(0)
		g.Id("_inScope").Op(":=").False()
		g.For(jen.List(jen.Id("_"), jen.Id("_rc")).Op(":=").Range().Add(ctx.root())).Block(
			jen.If(jen.Id("_rc").Dot("Kind").Op("==").Qual(cstPkg, "NodeArrayTable")).BlockFunc(func(g *jen.Group) {
				g.Id("_hdr").Op(":=").Qual(cstPkg, "TableHeaderKey").Call(jen.Id("_rc"))
				g.If(jen.Id("_hdr").Op("==").Add(pk.Jen())).Block(
					jen.If(jen.Id("_pi").Op("==").Id("i")).Block(jen.Id("_inScope").Op("=").True()).Else().If(jen.Id("_pi").Op(">").Id("i")).Block(jen.Break()),
					jen.Id("_pi").Op("++"), jen.Continue(),
				)
				g.If(jen.Id("_inScope").Op("&&").Id("_hdr").Op("==").Add(o.TDottedKey.Jen())).Block(
					jen.Id(nv).Op("=").Append(jen.Id(nv), jen.Id("_rc")),
				)
			}),
		)
		if o.SlicePointer {
			g.Add(o.Tgt.Jen().Clone()).Op("=").Make(jen.Index().Op("*").Id(o.TypeName), jen.Len(jen.Id(nv)))
		} else {
			g.Add(o.Tgt.Jen().Clone()).Op("=").Make(jen.Index().Id(o.TypeName), jen.Len(jen.Id(nv)))
		}
		g.Add(ctx.mc(o.TDottedKey))
		g.For(jen.List(jen.Id("_ii"), jen.Id("_nn")).Op(":=").Range().Id(nv)).BlockFunc(func(g *jen.Group) {
			if o.SlicePointer {
				g.Add(o.Tgt.Jen().Clone()).Index(jen.Id("_ii")).Op("=").Op("&").Id(o.TypeName).Values()
			}
			var leaf []DecodeOp
			for _, f := range o.Fields {
				switch f.(type) {
				case GetPrimitive, GetCustom, GetTextMarshaler, GetSlicePrimitive, GetSliceTextMarshaler:
					leaf = append(leaf, f)
				}
			}
			if len(leaf) > 0 {
				g.Add(jenLeafScan(ctx, leaf, jen.Id("_nn"), ""))
			}
		})
	})}
}

func jenPIPT(ctx jenCtx, o InPointerTable, pk TOMLKey) []jen.Code {
	lv := toLowerFirst(o.Tgt.Segs[len(o.Tgt.Segs)-1].Name) + "Val"
	return []jen.Code{jen.BlockFunc(func(g *jen.Group) {
		g.Var().Id("_ft").Op("*").Qual(cstPkg, "Node")
		g.Id("_pi").Op(":=").Lit(0)
		g.For(jen.List(jen.Id("_"), jen.Id("_rc")).Op(":=").Range().Add(ctx.root())).BlockFunc(func(g *jen.Group) {
			g.Add(posHeader(pk))
			g.If(jen.Id("_pi").Op("==").Id("i").Op("+").Lit(1).Op("&&").Id("_rc").Dot("Kind").Op("==").Qual(cstPkg, "NodeTable").Op("&&").Qual(cstPkg, "TableHeaderKey").Call(jen.Id("_rc")).Op("==").Add(o.TKey.Jen())).Block(
				jen.Id("_ft").Op("=").Id("_rc"), jen.Break(),
			)
		})
		g.If(jen.Id("_ft").Op("!=").Nil()).BlockFunc(func(g *jen.Group) {
			g.Add(ctx.mc(o.TKey))
			g.Id(lv).Op(":=").Op("&").Id(o.TypeName).Values()
			for _, s := range jenDecodeOps(ctx, o.TableFields, jen.Id("_ft"), "") {
				g.Add(s)
			}
			g.Add(o.Tgt.Jen().Clone()).Op("=").Id(lv)
		}).Else().BlockFunc(func(g *jen.Group) {
			g.Id(lv).Op(":=").Op("&").Id(o.TypeName).Values()
			g.Id("_found").Op(":=").False()
			for _, s := range jenDecodeOps(ctx, o.FlatFields, jen.Id("_node"), "_found") {
				g.Add(s)
			}
			g.If(jen.Id("_found")).Block(o.Tgt.Jen().Clone().Op("=").Id(lv))
		})
	})}
}

func jenPFMS(ctx jenCtx, o ForMapStringStruct, pk TOMLKey) []jen.Code {
	pf := o.TKey.Lit(".")
	return []jen.Code{jen.BlockFunc(func(g *jen.Group) {
		if o.SlicePointer {
			g.Var().Id("_mr").Map(jen.String()).Op("*").Id(o.TypeName)
		} else {
			g.Var().Id("_mr").Map(jen.String()).Id(o.TypeName)
		}
		g.Id("_pi").Op(":=").Lit(0)
		g.Id("_inScope").Op(":=").False()
		g.For(jen.List(jen.Id("_"), jen.Id("_rc")).Op(":=").Range().Add(ctx.root())).BlockFunc(func(g *jen.Group) {
			g.If(jen.Id("_rc").Dot("Kind").Op("==").Qual(cstPkg, "NodeArrayTable").Op("&&").Qual(cstPkg, "TableHeaderKey").Call(jen.Id("_rc")).Op("==").Add(pk.Jen())).Block(
				jen.If(jen.Id("_pi").Op("==").Id("i")).Block(jen.Id("_inScope").Op("=").True()).Else().If(jen.Id("_pi").Op(">").Id("i")).Block(jen.Break()),
				jen.Id("_pi").Op("++"), jen.Continue(),
			)
			g.If(jen.Id("_inScope").Op("&&").Id("_rc").Dot("Kind").Op("==").Qual(cstPkg, "NodeTable")).BlockFunc(func(g *jen.Group) {
				g.Id("_hdr").Op(":=").Qual(cstPkg, "TableHeaderKey").Call(jen.Id("_rc"))
				g.If(jen.Qual("strings", "HasPrefix").Call(jen.Id("_hdr"), pf.Jen())).BlockFunc(func(g *jen.Group) {
					g.Id("_mk").Op(":=").Id("_hdr").Index(pf.JenLen().Op(":"))
					g.If(jen.Qual("strings", "Contains").Call(jen.Id("_mk"), jen.Lit("."))).Block(jen.Continue())
					g.If(jen.Id("_mr").Op("==").Nil()).BlockFunc(func(g *jen.Group) {
						g.Add(ctx.mc(o.TKey))
						if o.SlicePointer {
							g.Id("_mr").Op("=").Make(jen.Map(jen.String()).Op("*").Id(o.TypeName))
						} else {
							g.Id("_mr").Op("=").Make(jen.Map(jen.String()).Id(o.TypeName))
						}
					})
					g.Add(ctx.mcExpr(o.TKey.Jen().Op("+").Lit(".").Op("+").Id("_mk")))
					g.Var().Id("entry").Id(o.TypeName)
					innerOps := injectMapKey(o.Fields, "_mk", o.TKey)
					for _, s := range jenDecodeOps(ctx, innerOps, jen.Id("_rc"), "") {
						g.Add(s)
					}
					if o.SlicePointer {
						g.Id("_mr").Index(jen.Id("_mk")).Op("=").Op("&").Id("entry")
					} else {
						g.Id("_mr").Index(jen.Id("_mk")).Op("=").Id("entry")
					}
				})
			})
		})
		g.If(jen.Id("_mr").Op("!=").Nil()).Block(o.Tgt.Jen().Clone().Op("=").Id("_mr"))
	})}
}

// --- Delegation ---

func jenDS(ctx jenCtx, o DelegateStruct) []jen.Code {
	_, st := delegateParts(o.TypeName)
	bk := o.TKey.BareKey()
	pk := o.TKey.Lit(".")
	decFn := "Decode" + st + "Into"

	if o.Pointer {
		lv := toLowerFirst(st) + "Val"
		return []jen.Code{jen.BlockFunc(func(g *jen.Group) {
			g.Var().Id("_tbl").Op("*").Qual(cstPkg, "Node")
			g.For(jen.List(jen.Id("_"), jen.Id("_ch")).Op(":=").Range().Add(ctx.root())).Block(
				jen.If(tableMatch(o.TKey)).Block(jen.Id("_tbl").Op("=").Id("_ch"), jen.Break()),
			)
			g.If(jen.Id("_tbl").Op("!=").Nil()).BlockFunc(func(g *jen.Group) {
				g.Add(ctx.mc(o.TKey))
				g.Id(lv).Op(":=").Op("&").Qual(o.ImportPath, st).Values()
				g.If(jen.Err().Op(":=").Qual(o.ImportPath, decFn).Call(
					jen.Id(lv), ctx.docVar.Clone(), jen.Id("_tbl"), ctx.consumed.Clone(), pk.Jen(),
				), jen.Err().Op("!=").Nil()).Block(ctx.retErr(bk+": %w", jen.Err()))
				g.Add(o.Tgt.Jen().Clone()).Op("=").Id(lv)
			})
		})}
	}
	return []jen.Code{jen.For(jen.List(jen.Id("_"), jen.Id("_ch")).Op(":=").Range().Add(ctx.root())).Block(
		jen.If(tableMatch(o.TKey)).BlockFunc(func(g *jen.Group) {
			g.Add(ctx.mc(o.TKey))
			g.If(jen.Err().Op(":=").Qual(o.ImportPath, decFn).Call(
				jen.Op("&").Add(o.Tgt.Jen().Clone()), ctx.docVar.Clone(), jen.Id("_ch"), ctx.consumed.Clone(), pk.Jen(),
			), jen.Err().Op("!=").Nil()).Block(ctx.retErr(bk+": %w", jen.Err()))
			g.Break()
		}),
	)}
}

func jenDSl(ctx jenCtx, o DelegateSlice, fv string) []jen.Code {
	_, st := delegateParts(o.TypeName)
	nv := "_" + tomlKey(o.Key) + "Nodes"
	pk := o.TDottedKey.Lit(".")
	decFn := "Decode" + st + "Into"

	var stmts []jen.Code
	stmts = append(stmts, jen.Var().Id(nv).Index().Op("*").Qual(cstPkg, "Node"))
	if o.TDottedKey.IsStatic() {
		stmts = append(stmts, jen.For(jen.List(jen.Id("_"), jen.Id("_ch")).Op(":=").Range().Add(ctx.root())).Block(
			jen.If(jen.Id("_ch").Dot("Kind").Op("==").Qual(cstPkg, "NodeArrayTable").Op("&&").Qual(cstPkg, "TableHeaderKey").Call(jen.Id("_ch")).Op("==").Add(o.TDottedKey.Jen())).Block(
				jen.Id(nv).Op("=").Append(jen.Id(nv), jen.Id("_ch")),
			),
		))
	} else {
		stmts = append(stmts, jen.Id(nv).Op("=").Add(ctx.docVar.Clone()).Dot("FindArrayTableNodes").Call(o.TDottedKey.Jen()))
	}
	if fv != "" {
		stmts = append(stmts, jen.If(jen.Len(jen.Id(nv)).Op(">").Lit(0)).Block(jen.Id(fv).Op("=").True()))
	}
	if o.SlicePointer {
		stmts = append(stmts, o.Tgt.Jen().Clone().Op("=").Make(jen.Index().Op("*").Qual(o.ImportPath, st), jen.Len(jen.Id(nv))))
	} else {
		stmts = append(stmts, o.Tgt.Jen().Clone().Op("=").Make(jen.Index().Qual(o.ImportPath, st), jen.Len(jen.Id(nv))))
	}
	stmts = append(stmts, ctx.mc(o.TDottedKey))
	stmts = append(stmts, jen.For(jen.List(jen.Id("i"), jen.Id("_node")).Op(":=").Range().Id(nv)).BlockFunc(func(g *jen.Group) {
		if o.SlicePointer {
			g.Add(o.Tgt.Jen().Clone()).Index(jen.Id("i")).Op("=").Op("&").Qual(o.ImportPath, st).Values()
			g.If(jen.Err().Op(":=").Qual(o.ImportPath, decFn).Call(
				o.Tgt.Jen().Clone().Index(jen.Id("i")), ctx.docVar.Clone(), jen.Id("_node"), ctx.consumed.Clone(), pk.Jen(),
			), jen.Err().Op("!=").Nil()).Block(ctx.retErr(tomlKey(o.Key)+"[%d]: %w", jen.Id("i"), jen.Err()))
		} else {
			g.If(jen.Err().Op(":=").Qual(o.ImportPath, decFn).Call(
				jen.Op("&").Add(o.Tgt.Jen().Clone()).Index(jen.Id("i")), ctx.docVar.Clone(), jen.Id("_node"), ctx.consumed.Clone(), pk.Jen(),
			), jen.Err().Op("!=").Nil()).Block(ctx.retErr(tomlKey(o.Key)+"[%d]: %w", jen.Id("i"), jen.Err()))
		}
	}))
	return stmts
}

func jenDM(ctx jenCtx, o DelegateMap) []jen.Code {
	_, st := delegateParts(o.ElemType)
	bk := o.TKey.BareKey()
	pf := o.TKey.Lit(".")
	decFn := "Decode" + st + "Into"

	return []jen.Code{jen.BlockFunc(func(g *jen.Group) {
		g.For(jen.List(jen.Id("_"), jen.Id("_ch")).Op(":=").Range().Add(ctx.root())).BlockFunc(func(g *jen.Group) {
			g.If(jen.Id("_ch").Dot("Kind").Op("!=").Qual(cstPkg, "NodeTable")).Block(jen.Continue())
			g.Id("_hdr").Op(":=").Qual(cstPkg, "TableHeaderKey").Call(jen.Id("_ch"))
			g.If(jen.Op("!").Qual("strings", "HasPrefix").Call(jen.Id("_hdr"), pf.Jen())).Block(jen.Continue())
			g.Id("_mk").Op(":=").Id("_hdr").Index(pf.JenLen().Op(":"))
			g.If(jen.Qual("strings", "Contains").Call(jen.Id("_mk"), jen.Lit("."))).Block(jen.Continue())
			g.If(o.Tgt.Jen().Clone().Op("==").Nil()).BlockFunc(func(g *jen.Group) {
				g.Add(ctx.mc(o.TKey))
				g.Add(o.Tgt.Jen().Clone()).Op("=").Make(jen.Map(jen.String()).Qual(o.ImportPath, st))
			})
			g.Add(ctx.mcExpr(o.TKey.Jen().Op("+").Lit(".").Op("+").Id("_mk")))
			g.Var().Id("entry").Qual(o.ImportPath, st)
			dke := o.TKey.Lit(".").Var("_mk").Lit(".")
			g.If(jen.Err().Op(":=").Qual(o.ImportPath, decFn).Call(
				jen.Op("&").Id("entry"), ctx.docVar.Clone(), jen.Id("_ch"), ctx.consumed.Clone(), dke.Jen(),
			), jen.Err().Op("!=").Nil()).Block(ctx.retErr(bk+".%s: %w", jen.Id("_mk"), jen.Err()))
			g.Add(o.Tgt.Jen().Clone()).Index(jen.Id("_mk")).Op("=").Id("entry")
		})
	})}
}

// --- Map key injection ---

func delegateParts(typeName string) (string, string) {
	if i := strings.IndexByte(typeName, '.'); i >= 0 {
		return typeName[:i], typeName[i+1:]
	}
	return "", typeName
}

// jenType returns a jennifer Code for a type name that might be cross-package.
// If importPath is non-empty, uses Qual; otherwise uses Id.
func jenType(typeName, importPath string) *jen.Statement {
	if importPath != "" {
		_, short := delegateParts(typeName)
		return jen.Qual(importPath, short)
	}
	return jen.Id(typeName)
}

func injectMapKey(ops []DecodeOp, mapVar string, parentKey TOMLKey) []DecodeOp {
	// Build the parent's literal suffix to match against inner key literals.
	// parentKey might be dynamic (has KeyPrefix), so we extract the literal tail.
	var parentLitSuffix string
	for _, p := range parentKey.Parts {
		if p.Kind == KeyLit {
			parentLitSuffix = p.Value
		}
	}
	matchSuffix := parentLitSuffix + "."

	mkPre := parentKey.Lit(".").Var(mapVar).Lit(".")
	rk := func(k TOMLKey) TOMLKey {
		// Replace the last literal part's matching prefix with the map key injection.
		// e.g., [KeyPrefix, KeyLit(".targets.host")] → [KeyPrefix, KeyLit(".targets."), KeyVar("_mk"), KeyLit(".host")]
		for i := len(k.Parts) - 1; i >= 0; i-- {
			if k.Parts[i].Kind == KeyLit {
				s := k.Parts[i].Value
				if strings.HasPrefix(s, matchSuffix) {
					rest := s[len(matchSuffix):]
					// Build new key: parts before this literal + mkPre parts + rest
					newParts := make([]KeyPart, i)
					copy(newParts, k.Parts[:i])
					for _, mp := range mkPre.Parts {
						newParts = append(newParts, mp)
					}
					if rest != "" {
						newParts = append(newParts, KeyPart{Kind: KeyLit, Value: rest})
					}
					return TOMLKey{Parts: newParts}
				}
				// For keys with a dot-separated prefix matching, try suffix match
				if idx := strings.Index(s, matchSuffix); idx >= 0 {
					rest := s[idx+len(matchSuffix):]
					pre := s[:idx]
					newParts := make([]KeyPart, i)
					copy(newParts, k.Parts[:i])
					if pre != "" {
						newParts = append(newParts, KeyPart{Kind: KeyLit, Value: pre})
					}
					for _, mp := range mkPre.Parts {
						newParts = append(newParts, mp)
					}
					if rest != "" {
						newParts = append(newParts, KeyPart{Kind: KeyLit, Value: rest})
					}
					return TOMLKey{Parts: newParts}
				}
				break
			}
		}
		return k
	}
	result := make([]DecodeOp, len(ops))
	for i, op := range ops {
		result[i] = injectMapKeyOp(op, rk)
	}
	return result
}

// ==========================================================================
// Encode renderer
// ==========================================================================

type encCtx struct {
	retErr  func(string, ...jen.Code) jen.Code
	rootVar *jen.Statement // d.cstDoc.Root() or doc.Root()
	docVar  *jen.Statement // d.cstDoc or doc — only for cross-package delegation
}

func receiverEncCtx() encCtx {
	return encCtx{
		retErr: func(f string, a ...jen.Code) jen.Code {
			args := []jen.Code{jen.Lit(f)}
			args = append(args, a...)
			return jen.Return(jen.Nil(), jen.Qual("fmt", "Errorf").Call(args...))
		},
		rootVar: jen.Id("d").Dot("cstDoc").Dot("Root").Call(),
		docVar:  jen.Id("d").Dot("cstDoc"),
	}
}

func freeEncCtx() encCtx {
	return encCtx{
		retErr: func(f string, a ...jen.Code) jen.Code {
			args := []jen.Code{jen.Lit(f)}
			args = append(args, a...)
			return jen.Return(jen.Qual("fmt", "Errorf").Call(args...))
		},
		rootVar: jen.Id("doc").Dot("Root").Call(),
		docVar:  jen.Id("doc"),
	}
}

func jenEncodeOps(ctx encCtx, ops []EncodeOp, cv *jen.Statement) []jen.Code {
	var out []jen.Code
	for _, op := range ops {
		out = append(out, jenEncodeOp(ctx, op, cv)...)
	}
	return out
}

func jenEncodeOp(ctx encCtx, op EncodeOp, cv *jen.Statement) []jen.Code {
	switch o := op.(type) {
	case SetPrimitive:
		return jenSetPrimitive(ctx, o, cv)
	case SetPointerPrimitive:
		return jenSetPointerPrimitive(ctx, o, cv)
	case SetCustom:
		return jenSetCustom(ctx, o, cv)
	case SetTextMarshaler:
		return jenSetTextMarshaler(ctx, o, cv)
	case SetSlicePrimitive:
		return jenSetSlicePrimitive(ctx, o, cv)
	case SetSliceTextMarshaler:
		return jenSetSliceTextMarshaler(ctx, o, cv)
	case SetMapStringString:
		return jenSetMapStringString(ctx, o, cv)
	case InEncodeTable:
		return jenInEncodeTable(ctx, o, cv)
	case InEncodePointerTable:
		return jenInEncodePointerTable(ctx, o, cv)
	case ForEncodeArrayTable:
		return jenForEncodeArrayTable(ctx, o)
	case ForEncodeMapStringStruct:
		return jenForEncodeMapStringStruct(ctx, o, cv)
	case ForEncodeMapStringMapStringString:
		return jenForEncodeMSMS(ctx, o, cv)
	case EncodeDelegateStruct:
		return jenEncDS(ctx, o, cv)
	case EncodeDelegateSlice:
		return jenEncDSl(ctx, o)
	case EncodeDelegateMap:
		return jenEncDM(ctx, o, cv)
	case EncodeValidate:
		return []jen.Code{
			jen.If(jen.Err().Op(":=").Add(o.DataTarget.Jen().Clone()).Dot("Validate").Call(), jen.Err().Op("!=").Nil()).Block(
				ctx.retErr("validation failed: %w", jen.Err()),
			),
		}
	}
	return nil
}

func jenSetCall(ctx encCtx, cv *jen.Statement, key TOMLKey, val *jen.Statement) jen.Code {
	return jen.If(jen.Err().Op(":=").Qual(cstPkg, "SetAny").Call(
		cv.Clone(), key.Jen(), val,
	), jen.Err().Op("!=").Nil()).Block(ctx.retErr("%w", jen.Err()))
}

func jenSetMultilineCall(ctx encCtx, cv *jen.Statement, key TOMLKey, val *jen.Statement) jen.Code {
	return jen.If(jen.Err().Op(":=").Qual(cstPkg, "SetMultilineString").Call(
		cv.Clone(), key.Jen(), val,
	), jen.Err().Op("!=").Nil()).Block(ctx.retErr("%w", jen.Err()))
}

func jenZeroLit(typeName string) *jen.Statement {
	switch typeName {
	case "bool":
		return jen.False()
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64":
		return jen.Lit(0)
	case "float32", "float64":
		return jen.Lit(0.0)
	case "string":
		return jen.Lit("")
	default:
		return jen.Lit("")
	}
}

func jenSetPrimitive(ctx encCtx, o SetPrimitive, cv *jen.Statement) []jen.Code {
	src := o.Tgt.Jen()
	bk := o.TKey.BareKey()
	zv := jenZeroLit(o.TypeName)
	encSrc := src.Clone()
	zvCmp := src.Clone()
	if o.ElemType != "" {
		// Cast alias to underlying type for SetInContainer: string(data.Version)
		encSrc = jen.Id(o.TypeName).Call(src.Clone())
		// Zero-value comparison: data.Version != types.Version("")
		zvCmp = src.Clone()
		zv = jenType(o.ElemType, o.ImportPath).Call(jenZeroLit(o.TypeName))
	}

	if o.OmitEmpty {
		var setStmt jen.Code
		if o.Multiline && o.TypeName == "string" {
			setStmt = jenSetMultilineCall(ctx, cv, StaticKey(bk), encSrc)
		} else {
			setStmt = jenSetCall(ctx, cv, StaticKey(bk), encSrc)
		}
		return []jen.Code{
			jen.If(zvCmp.Op("!=").Add(zv)).Block(setStmt).Else().Block(
				jen.Qual(cstPkg, "DeleteValue").Call(cv.Clone(), jen.Lit(bk)),
			),
		}
	}

	var setStmt jen.Code
	if o.Multiline && o.TypeName == "string" {
		setStmt = jenSetMultilineCall(ctx, cv, StaticKey(bk), encSrc)
	} else {
		setStmt = jenSetCall(ctx, cv, StaticKey(bk), encSrc)
	}
	return []jen.Code{
		jen.If(zvCmp.Op("!=").Add(zv).Op("||").Qual(cstPkg, "HasValue").Call(cv.Clone(), jen.Lit(bk))).Block(setStmt),
	}
}

func jenSetPointerPrimitive(ctx encCtx, o SetPointerPrimitive, cv *jen.Statement) []jen.Code {
	bk := o.TKey.BareKey()
	return []jen.Code{
		jen.If(o.Tgt.Jen().Clone().Op("!=").Nil()).Block(
			jenSetCall(ctx, cv, StaticKey(bk), jen.Op("*").Add(o.Tgt.Jen().Clone())),
		),
	}
}

func jenSetCustom(ctx encCtx, o SetCustom, cv *jen.Statement) []jen.Code {
	bk := o.TKey.BareKey()
	return []jen.Code{jen.BlockFunc(func(g *jen.Group) {
		g.List(jen.Id("v"), jen.Err()).Op(":=").Add(o.Tgt.Jen().Clone()).Dot("MarshalTOML").Call()
		g.If(jen.Err().Op("!=").Nil()).Block(ctx.retErr(bk+": %w", jen.Err()))
		g.Add(jenSetCall(ctx, cv, StaticKey(bk), jen.Id("v")))
	})}
}

func jenSetTextMarshaler(ctx encCtx, o SetTextMarshaler, cv *jen.Statement) []jen.Code {
	bk := o.TKey.BareKey()
	return []jen.Code{jen.BlockFunc(func(g *jen.Group) {
		g.List(jen.Id("v"), jen.Err()).Op(":=").Add(o.Tgt.Jen().Clone()).Dot("MarshalText").Call()
		g.If(jen.Err().Op("!=").Nil()).Block(ctx.retErr(bk+": %w", jen.Err()))
		if o.OmitEmpty {
			g.If(jen.Len(jen.Id("v")).Op(">").Lit(0)).Block(
				jenSetCall(ctx, cv, StaticKey(bk), jen.String().Call(jen.Id("v"))),
			).Else().Block(
				jen.Qual(cstPkg, "DeleteValue").Call(cv.Clone(), jen.Lit(bk)),
			)
		} else {
			g.Add(jenSetCall(ctx, cv, StaticKey(bk), jen.String().Call(jen.Id("v"))))
		}
	})}
}

func jenSetSlicePrimitive(ctx encCtx, o SetSlicePrimitive, cv *jen.Statement) []jen.Code {
	bk := o.TKey.BareKey()
	src := o.Tgt.Jen()
	return []jen.Code{jen.BlockFunc(func(g *jen.Group) {
		if o.OmitEmpty {
			g.If(jen.Len(src.Clone()).Op(">").Lit(0).Op("||").Qual(cstPkg, "HasValue").Call(cv.Clone(), jen.Lit(bk))).BlockFunc(func(g *jen.Group) {
				g.Add(jenSlicePrimSet(ctx, o, cv, bk))
			})
		} else {
			g.Add(jenSlicePrimSet(ctx, o, cv, bk))
		}
	})}
}

func jenSlicePrimSet(ctx encCtx, o SetSlicePrimitive, cv *jen.Statement, bk string) jen.Code {
	src := o.Tgt.Jen()
	if o.SlicePointer {
		tmpVar := "tmp" + o.Tgt.Segs[len(o.Tgt.Segs)-1].Name
		return jen.BlockFunc(func(g *jen.Group) {
			g.Id(tmpVar).Op(":=").Make(jen.Index().Id(o.ElemType), jen.Lit(0), jen.Len(src.Clone()))
			g.For(jen.List(jen.Id("_"), jen.Id("p")).Op(":=").Range().Add(src.Clone())).Block(
				jen.If(jen.Id("p").Op("!=").Nil()).Block(
					jen.Id(tmpVar).Op("=").Append(jen.Id(tmpVar), jen.Op("*").Id("p")),
				),
			)
			g.Add(jenSetCall(ctx, cv, StaticKey(bk), jen.Id(tmpVar)))
		})
	}
	var encSrc *jen.Statement
	if o.TypeName != "" {
		encSrc = jen.Index().Id(o.ElemType).Call(src.Clone())
	} else {
		encSrc = src.Clone()
	}
	return jenSetCall(ctx, cv, StaticKey(bk), encSrc)
}

func jenSetSliceTextMarshaler(ctx encCtx, o SetSliceTextMarshaler, cv *jen.Statement) []jen.Code {
	bk := o.TKey.BareKey()
	src := o.Tgt.Jen()
	return []jen.Code{jen.BlockFunc(func(g *jen.Group) {
		g.Id("vals").Op(":=").Make(jen.Index().String(), jen.Len(src.Clone()))
		g.For(jen.List(jen.Id("i"), jen.Id("item")).Op(":=").Range().Add(src.Clone())).Block(
			jen.List(jen.Id("v"), jen.Err()).Op(":=").Id("item").Dot("MarshalText").Call(),
			jen.If(jen.Err().Op("!=").Nil()).Block(ctx.retErr(bk+"[%d]: %w", jen.Id("i"), jen.Err())),
			jen.Id("vals").Index(jen.Id("i")).Op("=").String().Call(jen.Id("v")),
		)
		g.Add(jenSetCall(ctx, cv, StaticKey(bk), jen.Id("vals")))
	})}
}

func jenSetMapStringString(ctx encCtx, o SetMapStringString, cv *jen.Statement) []jen.Code {
	bk := o.TKey.BareKey()
	src := o.Tgt.Jen()
	return []jen.Code{
		jen.If(jen.Len(src.Clone()).Op(">").Lit(0)).BlockFunc(func(g *jen.Group) {
			if o.UseRootAPI {
				g.Id("tableNode").Op(":=").Qual(cstPkg, "EnsureChildTable").Call(ctx.rootVar.Clone(), ctx.rootVar.Clone(), jen.Lit(bk))
			} else {
				g.Id("tableNode").Op(":=").Qual(cstPkg, "EnsureChildTable").Call(ctx.rootVar.Clone(), cv.Clone(), jen.Lit(bk))
			}
			g.Qual(cstPkg, "DeleteAllValues").Call(jen.Id("tableNode"))
			g.For(jen.List(jen.Id("k"), jen.Id("v")).Op(":=").Range().Add(src.Clone())).Block(
				jen.If(jen.Err().Op(":=").Qual(cstPkg, "SetAny").Call(
					jen.Id("tableNode"), jen.Id("k"), jen.Id("v"),
				), jen.Err().Op("!=").Nil()).Block(ctx.retErr("%w", jen.Err())),
			)
		}),
	}
}

func encodeFieldsNeedContainer(ops []EncodeOp) bool {
	for _, op := range ops {
		switch op.(type) {
		case ForEncodeArrayTable, EncodeDelegateSlice:
			continue
		default:
			return true
		}
	}
	return false
}

func jenInEncodeTable(ctx encCtx, o InEncodeTable, cv *jen.Statement) []jen.Code {
	bk := o.TKey.BareKey()
	needsTable := encodeFieldsNeedContainer(o.Fields)
	return []jen.Code{jen.BlockFunc(func(g *jen.Group) {
		if needsTable {
			if o.UseRootAPI {
				g.Id("tableNode").Op(":=").Qual(cstPkg, "EnsureChildTable").Call(ctx.rootVar.Clone(), ctx.rootVar.Clone(), jen.Lit(bk))
			} else {
				g.Id("tableNode").Op(":=").Qual(cstPkg, "EnsureChildTable").Call(ctx.rootVar.Clone(), cv.Clone(), jen.Lit(bk))
			}
		} else {
			if o.UseRootAPI {
				g.Id("_").Op("=").Qual(cstPkg, "EnsureChildTable").Call(ctx.rootVar.Clone(), ctx.rootVar.Clone(), jen.Lit(bk))
			} else {
				g.Id("_").Op("=").Qual(cstPkg, "EnsureChildTable").Call(ctx.rootVar.Clone(), cv.Clone(), jen.Lit(bk))
			}
		}
		for _, s := range jenEncodeOps(ctx, o.Fields, jen.Id("tableNode")) {
			g.Add(s)
		}
	})}
}

func jenInEncodePointerTable(ctx encCtx, o InEncodePointerTable, cv *jen.Statement) []jen.Code {
	bk := o.TKey.BareKey()
	needsTable := encodeFieldsNeedContainer(o.Fields)
	return []jen.Code{
		jen.If(o.Tgt.Jen().Clone().Op("!=").Nil()).BlockFunc(func(g *jen.Group) {
			if needsTable {
				g.Id("tableNode").Op(":=").Qual(cstPkg, "EnsureChildTable").Call(ctx.rootVar.Clone(), cv.Clone(), jen.Lit(bk))
			} else {
				g.Id("_").Op("=").Qual(cstPkg, "EnsureChildTable").Call(ctx.rootVar.Clone(), cv.Clone(), jen.Lit(bk))
			}
			for _, s := range jenEncodeOps(ctx, o.Fields, jen.Id("tableNode")) {
				g.Add(s)
			}
		}),
	}
}

func jenForEncodeArrayTable(ctx encCtx, o ForEncodeArrayTable) []jen.Code {
	src := o.Tgt.Jen()
	bk := o.TKey.BareKey()

	return []jen.Code{jen.BlockFunc(func(g *jen.Group) {
		if o.TrackHandles {
			handleSlice := "d." + toLowerFirst(o.Tgt.Segs[len(o.Tgt.Segs)-1].Name)
			g.For(jen.Id("i").Op(":=").Range().Add(src.Clone())).BlockFunc(func(g *jen.Group) {
				g.Var().Id("container").Op("*").Qual(cstPkg, "Node")
				g.If(jen.Id("i").Op("<").Len(jen.Id(handleSlice))).Block(
					jen.Id("container").Op("=").Id(handleSlice).Index(jen.Id("i")).Dot("node"),
				).Else().Block(
					jen.Id("container").Op("=").Qual(cstPkg, "AppendArrayTableEntryAfter").Call(ctx.rootVar.Clone(), jen.Lit(bk)),
				)
				for _, s := range jenEncodeOps(ctx, o.Fields, jen.Id("container")) {
					g.Add(s)
				}
			})
		} else {
			existVar := bk + "Existing"
			g.Id(existVar).Op(":=").Qual(cstPkg, "FindArrayTableNodes").Call(ctx.rootVar.Clone(), o.TDottedKey.Jen())
			g.For(jen.Id("i").Op(":=").Range().Add(src.Clone())).BlockFunc(func(g *jen.Group) {
				g.Var().Id("container").Op("*").Qual(cstPkg, "Node")
				g.If(jen.Id("i").Op("<").Len(jen.Id(existVar))).Block(
					jen.Id("container").Op("=").Id(existVar).Index(jen.Id("i")),
				).Else().Block(
					jen.Id("container").Op("=").Qual(cstPkg, "AppendArrayTableEntryAfter").Call(ctx.rootVar.Clone(), o.TDottedKey.Jen()),
				)
				for _, s := range jenEncodeOps(ctx, o.Fields, jen.Id("container")) {
					g.Add(s)
				}
			})
		}
	})}
}

func jenForEncodeMapStringStruct(ctx encCtx, o ForEncodeMapStringStruct, cv *jen.Statement) []jen.Code {
	bk := o.TKey.BareKey()
	src := o.Tgt.Jen()

	return []jen.Code{
		jen.If(jen.Len(src.Clone()).Op(">").Lit(0)).BlockFunc(func(g *jen.Group) {
			g.For(jen.List(jen.Id("mapKey"), jen.Id("mapVal")).Op(":=").Range().Add(src.Clone())).BlockFunc(func(g *jen.Group) {
				needsSub := encodeFieldsNeedContainer(o.Fields)
				parentForSub := cv.Clone()
				if o.UseRootAPI {
					parentForSub = ctx.rootVar.Clone()
				}
				if needsSub {
					g.Id("subTable").Op(":=").Qual(cstPkg, "EnsureChildSubTable").Call(ctx.rootVar.Clone(), parentForSub, jen.Lit(bk), jen.Id("mapKey"))
				} else {
					g.Id("_").Op("=").Qual(cstPkg, "EnsureChildSubTable").Call(ctx.rootVar.Clone(), parentForSub, jen.Lit(bk), jen.Id("mapKey"))
				}
				if o.SlicePointer {
					g.If(jen.Id("mapVal").Op("==").Nil()).Block(jen.Continue())
				}
				for _, s := range jenEncodeOps(ctx, o.Fields, jen.Id("subTable")) {
					g.Add(s)
				}
			})
		}),
	}
}

func jenForEncodeMSMS(ctx encCtx, o ForEncodeMapStringMapStringString, cv *jen.Statement) []jen.Code {
	bk := o.TKey.BareKey()
	src := o.Tgt.Jen()
	return []jen.Code{
		jen.If(jen.Len(src.Clone()).Op(">").Lit(0)).BlockFunc(func(g *jen.Group) {
			g.For(jen.List(jen.Id("mapKey"), jen.Id("mapVal")).Op(":=").Range().Add(src.Clone())).Block(
				jen.Id("subTable").Op(":=").Qual(cstPkg, "EnsureChildSubTable").Call(ctx.rootVar.Clone(), ctx.rootVar.Clone(), jen.Lit(bk), jen.Id("mapKey")),
				jen.Qual(cstPkg, "DeleteAllValues").Call(jen.Id("subTable")),
				jen.For(jen.List(jen.Id("k"), jen.Id("v")).Op(":=").Range().Map(jen.String()).String().Call(jen.Id("mapVal"))).Block(
					jen.If(jen.Err().Op(":=").Qual(cstPkg, "SetAny").Call(
						jen.Id("subTable"), jen.Id("k"), jen.Id("v"),
					), jen.Err().Op("!=").Nil()).Block(ctx.retErr("%w", jen.Err())),
				),
			)
		}),
	}
}

func jenEncDS(ctx encCtx, o EncodeDelegateStruct, cv *jen.Statement) []jen.Code {
	_, st := delegateParts(o.TypeName)
	bk := o.TKey.BareKey()
	encFn := "Encode" + st + "From"

	if o.Pointer {
		return []jen.Code{
			jen.If(o.Tgt.Jen().Clone().Op("!=").Nil()).BlockFunc(func(g *jen.Group) {
				g.Id("tableNode").Op(":=").Qual(cstPkg, "EnsureChildTable").Call(ctx.rootVar.Clone(), cv.Clone(), jen.Lit(bk))
				g.If(jen.Err().Op(":=").Qual(o.ImportPath, encFn).Call(
					o.Tgt.Jen().Clone(), ctx.docVar.Clone(), jen.Id("tableNode"),
				), jen.Err().Op("!=").Nil()).Block(ctx.retErr(bk+": %w", jen.Err()))
			}),
		}
	}
	return []jen.Code{jen.BlockFunc(func(g *jen.Group) {
		if o.UseRootAPI {
			g.Id("tableNode").Op(":=").Qual(cstPkg, "EnsureChildTable").Call(ctx.rootVar.Clone(), ctx.rootVar.Clone(), jen.Lit(bk))
		} else {
			g.Id("tableNode").Op(":=").Qual(cstPkg, "EnsureChildTable").Call(ctx.rootVar.Clone(), cv.Clone(), jen.Lit(bk))
		}
		g.If(jen.Err().Op(":=").Qual(o.ImportPath, encFn).Call(
			jen.Op("&").Add(o.Tgt.Jen().Clone()), ctx.docVar.Clone(), jen.Id("tableNode"),
		), jen.Err().Op("!=").Nil()).Block(ctx.retErr(bk+": %w", jen.Err()))
	})}
}

func jenEncDSl(ctx encCtx, o EncodeDelegateSlice) []jen.Code {
	_, st := delegateParts(o.TypeName)
	bk := o.TKey.BareKey()
	encFn := "Encode" + st + "From"
	src := o.Tgt.Jen()

	return []jen.Code{jen.BlockFunc(func(g *jen.Group) {
		existVar := bk + "Existing"
		g.Id(existVar).Op(":=").Qual(cstPkg, "FindArrayTableNodes").Call(ctx.rootVar.Clone(), o.TDottedKey.Jen())
		g.For(jen.Id("i").Op(":=").Range().Add(src.Clone())).BlockFunc(func(g *jen.Group) {
			g.Var().Id("container").Op("*").Qual(cstPkg, "Node")
			g.If(jen.Id("i").Op("<").Len(jen.Id(existVar))).Block(
				jen.Id("container").Op("=").Id(existVar).Index(jen.Id("i")),
			).Else().Block(
				jen.Id("container").Op("=").Qual(cstPkg, "AppendArrayTableEntryAfter").Call(ctx.rootVar.Clone(), jen.Lit(bk)),
			)
			if o.SlicePointer {
				g.If(jen.Err().Op(":=").Qual(o.ImportPath, encFn).Call(
					src.Clone().Index(jen.Id("i")), ctx.docVar.Clone(), jen.Id("container"),
				), jen.Err().Op("!=").Nil()).Block(ctx.retErr(bk+"[%d]: %w", jen.Id("i"), jen.Err()))
			} else {
				g.If(jen.Err().Op(":=").Qual(o.ImportPath, encFn).Call(
					jen.Op("&").Add(src.Clone()).Index(jen.Id("i")), ctx.docVar.Clone(), jen.Id("container"),
				), jen.Err().Op("!=").Nil()).Block(ctx.retErr(bk+"[%d]: %w", jen.Id("i"), jen.Err()))
			}
		})
	})}
}

func jenEncDM(ctx encCtx, o EncodeDelegateMap, cv *jen.Statement) []jen.Code {
	_, st := delegateParts(o.ElemType)
	bk := o.TKey.BareKey()
	encFn := "Encode" + st + "From"
	src := o.Tgt.Jen()

	return []jen.Code{
		jen.If(jen.Len(src.Clone()).Op(">").Lit(0)).BlockFunc(func(g *jen.Group) {
			g.For(jen.List(jen.Id("mapKey"), jen.Id("mapVal")).Op(":=").Range().Add(src.Clone())).BlockFunc(func(g *jen.Group) {
				parentForSub := cv.Clone()
				if o.UseRootAPI {
					parentForSub = ctx.rootVar.Clone()
				}
				g.Id("subTable").Op(":=").Qual(cstPkg, "EnsureChildSubTable").Call(ctx.rootVar.Clone(), parentForSub, jen.Lit(bk), jen.Id("mapKey"))
				g.If(jen.Err().Op(":=").Qual(o.ImportPath, encFn).Call(
					jen.Op("&").Id("mapVal"), ctx.docVar.Clone(), jen.Id("subTable"),
				), jen.Err().Op("!=").Nil()).Block(ctx.retErr(bk+".%s: %w", jen.Id("mapKey"), jen.Err()))
			})
		}),
	}
}

// --- Map key injection (decode) ---

func injectMapKeyOp(op DecodeOp, rk func(TOMLKey) TOMLKey) DecodeOp {
	switch o := op.(type) {
	case GetPrimitive:
		o.TKey = rk(o.TKey)
		return o
	case GetCustom:
		o.TKey = rk(o.TKey)
		return o
	case GetTextMarshaler:
		o.TKey = rk(o.TKey)
		return o
	case GetSlicePrimitive:
		o.TKey = rk(o.TKey)
		return o
	case GetSliceTextMarshaler:
		o.TKey = rk(o.TKey)
		return o
	case GetMapStringString:
		o.TKey = rk(o.TKey)
		return o
	case GetMapStringMapStringString:
		o.TKey = rk(o.TKey)
		return o
	case InTable:
		o.TKey = rk(o.TKey)
		o.Fields = injectMapKey(o.Fields, "", TOMLKey{})
		return o
	case InPointerTable:
		o.TKey = rk(o.TKey)
		return o
	case ForArrayTable:
		o.TKey = rk(o.TKey)
		o.TDottedKey = rk(o.TDottedKey)
		return o
	case ForMapStringStruct:
		o.TKey = rk(o.TKey)
		return o
	case DelegateStruct:
		o.TKey = rk(o.TKey)
		return o
	case DelegateSlice:
		o.TKey = rk(o.TKey)
		o.TDottedKey = rk(o.TDottedKey)
		return o
	case DelegateMap:
		o.TKey = rk(o.TKey)
		return o
	case WithFoundVar:
		o.Inner = injectMapKeyOp(o.Inner, rk)
		return o
	}
	return op
}
