package generate

import (
	"bytes"
	"strings"
	"testing"
)

func TestTemplateRendersHeader(t *testing.T) {
	si := StructInfo{
		Name: "Config",
		Fields: []FieldInfo{
			{GoName: "Name", TomlKey: "name", Kind: FieldPrimitive, TypeName: "string"},
		},
	}

	var buf bytes.Buffer
	err := RenderFile(&buf, "testpkg", []StructInfo{si})
	if err != nil {
		t.Fatal(err)
	}

	out := buf.String()
	if !strings.Contains(out, "Code generated by tommy; DO NOT EDIT.") {
		t.Fatal("missing generated header")
	}
	if !strings.Contains(out, "package testpkg") {
		t.Fatal("missing package declaration")
	}
	if !strings.Contains(out, "ConfigDocument") {
		t.Fatal("missing ConfigDocument type")
	}
	if !strings.Contains(out, "DecodeConfig") {
		t.Fatal("missing DecodeConfig function")
	}
	if !strings.Contains(out, "func (d *ConfigDocument) Data() *Config") {
		t.Fatal("missing Data() method")
	}
	if !strings.Contains(out, "func (d *ConfigDocument) Encode() ([]byte, error)") {
		t.Fatal("missing Encode() method")
	}
}

func TestTemplateRendersUnexportedHandle(t *testing.T) {
	si := StructInfo{
		Name: "Config",
		Fields: []FieldInfo{
			{
				GoName: "Servers", TomlKey: "servers", Kind: FieldSliceStruct,
				TypeName: "Server",
				InnerInfo: &StructInfo{
					Name: "Server",
					Fields: []FieldInfo{
						{GoName: "Name", TomlKey: "name", Kind: FieldPrimitive, TypeName: "string"},
					},
				},
			},
		},
	}

	var buf bytes.Buffer
	err := RenderFile(&buf, "testpkg", []StructInfo{si})
	if err != nil {
		t.Fatal(err)
	}

	out := buf.String()
	if !strings.Contains(out, "serverHandle") {
		t.Fatal("missing unexported serverHandle type")
	}
}
