package generate

import (
	"io"
	"strings"
	"text/template"
	"unicode"
)

const fileTemplate = `// Code generated by tommy; DO NOT EDIT.

package {{.Package}}

import (
	"fmt"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)
{{range .Structs}}
{{- range .Fields}}{{if eq (kindInt .Kind) 4}}
type {{unexport .TypeName}}Handle struct {
	node *cst.Node
}
{{end}}{{end}}
type {{.Name}}Document struct {
	data   {{.Name}}
	cstDoc *document.Document
{{- range .Fields}}{{if eq (kindInt .Kind) 4}}
	{{unexport .GoName}} []{{unexport .TypeName}}Handle
{{- end}}{{end}}
}

func Decode{{.Name}}(input []byte) (*{{.Name}}Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &{{.Name}}Document{cstDoc: doc}

{{emitDecode .}}
	return d, nil
}

func (d *{{.Name}}Document) Data() *{{.Name}} { return &d.data }

func (d *{{.Name}}Document) Encode() ([]byte, error) {
{{emitEncode .}}
	return d.cstDoc.Bytes(), nil
}
{{end}}`

type fileData struct {
	Package string
	Structs []StructInfo
}

func unexport(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func RenderFile(w io.Writer, pkg string, structs []StructInfo) error {
	tmpl := template.Must(template.New("file").Funcs(template.FuncMap{
		"unexport":   unexport,
		"lower":      strings.ToLower,
		"kindInt":    func(k FieldKind) int { return int(k) },
		"emitDecode": func(si StructInfo) string { return emitDecodeBody(si) },
		"emitEncode": func(si StructInfo) string { return emitEncodeBody(si) },
	}).Parse(fileTemplate))

	return tmpl.Execute(w, fileData{
		Package: pkg,
		Structs: structs,
	})
}
