package generate

import (
	"io"
	"strings"
	"text/template"
	"unicode"
)

const fileTemplate = `// Code generated by tommy; DO NOT EDIT.

package {{.Package}}

import (
	"fmt"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
{{- range .ExtraImports}}
	"{{.}}"
{{- end}}
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)
{{range .Structs}}
{{- range .Fields}}{{if eq (kindInt .Kind) 4}}
type {{unexport .TypeName}}Handle struct {
	node *cst.Node
}
{{end}}{{end}}
type {{.Name}}Document struct {
	data     {{.Name}}
	cstDoc   *document.Document
	consumed map[string]bool
{{- range .Fields}}{{if eq (kindInt .Kind) 4}}
	{{unexport .GoName}} []{{unexport .TypeName}}Handle
{{- end}}{{end}}
}

func Decode{{.Name}}(input []byte) (*{{.Name}}Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &{{.Name}}Document{cstDoc: doc, consumed: make(map[string]bool)}

{{emitDecode .}}
	return d, nil
}

func (d *{{.Name}}Document) Data() *{{.Name}} { return &d.data }

func (d *{{.Name}}Document) Encode() ([]byte, error) {
{{emitEncode .}}
	return d.cstDoc.Bytes(), nil
}

func (d *{{.Name}}Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

func (d *{{.Name}}Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *{{.Name}}Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *{{.Name}}Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *{{.Name}}Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func Decode{{.Name}}Into(data *{{.Name}}, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
{{emitDecodeInto .}}
	return nil
}

func Encode{{.Name}}From(data *{{.Name}}, doc *document.Document, container *cst.Node) error {
{{emitEncodeFrom .}}
	return nil
}
{{end}}`

type fileData struct {
	Package      string
	Structs      []StructInfo
	ExtraImports []string
}

func unexport(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func collectImportPaths(structs []StructInfo) []string {
	seen := make(map[string]bool)
	for _, si := range structs {
		collectFieldImports(si.Fields, seen)
	}
	var paths []string
	for p := range seen {
		paths = append(paths, p)
	}
	return paths
}

func collectFieldImports(fields []FieldInfo, seen map[string]bool) {
	for _, fi := range fields {
		if fi.ImportPath != "" {
			seen[fi.ImportPath] = true
		}
		// Don't recurse into delegated fields — their inner imports are
		// handled by the target package's generated code, not ours.
		if fi.InnerInfo != nil && fi.Kind != FieldDelegatedStruct && fi.Kind != FieldPointerDelegatedStruct {
			collectFieldImports(fi.InnerInfo.Fields, seen)
		}
	}
}

func RenderFile(w io.Writer, pkg string, structs []StructInfo) error {
	tmpl := template.Must(template.New("file").Funcs(template.FuncMap{
		"unexport":   unexport,
		"lower":      strings.ToLower,
		"kindInt":    func(k FieldKind) int { return int(k) },
		"emitDecode":     func(si StructInfo) string { return emitDecodeBody(si) },
		"emitEncode":     func(si StructInfo) string { return emitEncodeBody(si) },
		"emitDecodeInto": func(si StructInfo) string { return emitDecodeIntoBody(si) },
		"emitEncodeFrom": func(si StructInfo) string { return emitEncodeFromBody(si) },
	}).Parse(fileTemplate))

	return tmpl.Execute(w, fileData{
		Package:      pkg,
		Structs:      structs,
		ExtraImports: collectImportPaths(structs),
	})
}
