// Code generated by tommy 0.5.0 (0000000); DO NOT EDIT.

package config

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type ConfigDocument struct {
	data   Config
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeConfig(input []byte) (*ConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &ConfigDocument{
		cstDoc: doc,
		model:  model,
	}

	if _vName, _ok := model.Get("name"); _ok && _vName.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vName.Leaf); _xok {
			d.data.Name = _x
			_vName.MarkConsumed()
		}
	}
	if _vPort, _ok := model.Get("port"); _ok && _vPort.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractInt(_vPort.Leaf); _xok {
			d.data.Port = _x
			_vPort.MarkConsumed()
		}
	}
	if _vTags, _ok := model.Get("tags"); _ok && _vTags.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vTags.Leaf); _xok {
			d.data.Tags = _x
			if d.data.Tags == nil {
				d.data.Tags = []string{}
			}
			_vTags.MarkConsumed()
		}
	}
	if _vLabels, _ok := model.Get("labels"); _ok && _vLabels.Kind == cst.VTable {
		_vLabels.MarkSeen()
		d.data.Labels = make(map[string]string)
		for _iLabels := range _vLabels.Fields {
			_fLabels := &_vLabels.Fields[_iLabels]
			if _fLabels.Val.Kind == cst.VLeaf {
				if _s, _sok := cst.ExtractString(_fLabels.Val.Leaf); _sok {
					d.data.Labels[_fLabels.Key] = _s
					_fLabels.Val.MarkConsumed()
				}
			}
		}
	}
	return d, nil
}

func (d *ConfigDocument) Data() *Config {
	return &d.data
}

func (d *ConfigDocument) Encode() ([]byte, error) {
	if d.data.Name != "" || cst.HasValue(d.cstDoc.Root(), "name") {
		if err := cst.SetAny(d.cstDoc.Root(), "name", d.data.Name); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Port != 0 {
		if err := cst.SetAny(d.cstDoc.Root(), "port", d.data.Port); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "port")
	}
	{
		if d.data.Tags != nil {
			if err := cst.SetAny(d.cstDoc.Root(), "tags", d.data.Tags); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.Labels != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "labels")
		cst.DeleteAllValues(tableNode)
		for k, v := range d.data.Labels {
			if err := cst.SetAny(tableNode, k, v); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *ConfigDocument) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *ConfigDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *ConfigDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *ConfigDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *ConfigDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeConfigInto(data *Config, sub *cst.Value) error {
	if _vName, _ok := sub.Get("name"); _ok && _vName.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vName.Leaf); _xok {
			data.Name = _x
			_vName.MarkConsumed()
		}
	}
	if _vPort, _ok := sub.Get("port"); _ok && _vPort.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractInt(_vPort.Leaf); _xok {
			data.Port = _x
			_vPort.MarkConsumed()
		}
	}
	if _vTags, _ok := sub.Get("tags"); _ok && _vTags.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vTags.Leaf); _xok {
			data.Tags = _x
			if data.Tags == nil {
				data.Tags = []string{}
			}
			_vTags.MarkConsumed()
		}
	}
	if _vLabels, _ok := sub.Get("labels"); _ok && _vLabels.Kind == cst.VTable {
		_vLabels.MarkSeen()
		data.Labels = make(map[string]string)
		for _iLabels := range _vLabels.Fields {
			_fLabels := &_vLabels.Fields[_iLabels]
			if _fLabels.Val.Kind == cst.VLeaf {
				if _s, _sok := cst.ExtractString(_fLabels.Val.Leaf); _sok {
					data.Labels[_fLabels.Key] = _s
					_fLabels.Val.MarkConsumed()
				}
			}
		}
	}
	return nil
}

func EncodeConfigFrom(data *Config, doc *document.Document, container *cst.Node) error {
	if data.Name != "" || cst.HasValue(container, "name") {
		if err := cst.SetAny(container, "name", data.Name); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Port != 0 {
		if err := cst.SetAny(container, "port", data.Port); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "port")
	}
	{
		if data.Tags != nil {
			if err := cst.SetAny(container, "tags", data.Tags); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.Labels != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "labels")
		cst.DeleteAllValues(tableNode)
		for k, v := range data.Labels {
			if err := cst.SetAny(tableNode, k, v); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	return nil
}
